name: Xiaoxin template

on:
  pull_request:
    branches: [ main ]
  # schedule: 
  #   # * is a special character in YAML so you have to quote this string
  #   - cron: "*/5 * * * *"  # Runs every 5 mins
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  build:

    runs-on: ubuntu-latest

  steps:

  # Step 1: Checkout the repository and provide your AWS credentials
  - name: Checkout repository
    uses: actions/checkout@v2
    with:
      fetch-depth: 0

  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-west-2  # Region to access CodeGuru 

  # Step 2: Add CodeGuru Reviewer Action
  - name: CodeGuru Reviewer
    uses: aws-actions/codeguru-reviewer@v1.1
    with:
      build_path: target # build artifact(s) directory
      s3_bucket: codeguru-reviewer-github-xxz-test  # S3 Bucket with "codeguru-reviewer-*" prefix
   
  # Step 3: Upload results into GitHub
  - name: Upload review result
    uses: github/codeql-action/upload-sarif@v1
    with:
      sarif_file: codeguru-results.sarif.json
